name: restauapp
description: "A new Flutter project for restaurants."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.0

  # Core
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  intl: ^0.19.0
  # UI Components
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Images & Media
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  
  # System & Utils
  url_launcher: ^6.2.2
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/restaurants_images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700